---
services: docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python python-pip docker

install:
  # Install ansible
  - sudo pip install ansible
  - sudo pip install docker-py
  - echo -e 'localhost  ansible_connection=local' > tests/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./tests/inventory' > ansible.cfg

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook --syntax-check tests/test.yml
  - ansible-playbook -v --diff tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
