---
- name: Enable auditd.service
  shell: systemctl enable auditd

- name: Apply audit rules
  template: src=audit.rules.j2 dest=/etc/audit/rules.d/audit.rules owner=root group=root mode=0640

- name: Start auditd.service
  shell: systemctl start auditd

- name: Reload audit rules
  shell: auditctl -R /etc/audit/rules.d/audit.rules
